name: Lint

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*"
      - "src/**"
defaults:
  run:
    working-directory: ./

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync

      - name: Check code formatting with autopep8
        run: uv run pycodestyle src/**.py --max-line-length 120 --ignore E221,E222,E501,W503

      - name: Run Ruff linters
        run: uv run ruff check .
